const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const R=require('../src/core.js');const fixtures=require('./fixtures-r9.json');const close=(a,b)=>assert.ok(Math.abs(a-Number(b))<=1e-12,`${a} != ${b}`);
const issue=require('./fixtures-issue39.json');assert.equal(issue.length,10);for(const x of issue){const local=fixtures.find(r=>r.comparison_id===x.comparison_id);for(const [k,v] of Object.entries(x))assert.equal(String(local[k]),v,k);const [k,g]=R.minimumGap(Number(x.N));close(k,x.minimum_gap_questions);close(g,x.minimum_gap);assert.equal(String(Math.abs(Number(x.gap))<g),x.below_minimum_gap.toLowerCase());}
assert.equal(fixtures.length,10);
for(const x of fixtures){const n=Number(x.N),a=Number(x.score_A),b=Number(x.score_B);const wa=R.wilson(a,n),wb=R.wilson(b,n),d=R.difference(a,b,n);wa.forEach((v,i)=>close(v,x[i?'wilson_upper_A':'wilson_lower_A']));wb.forEach((v,i)=>close(v,x[i?'wilson_upper_B':'wilson_lower_B']));d.forEach((v,i)=>close(v,x[i?'item_upper':'item_lower']));assert.equal(R.verdict(...d),x.item_noise_verdict);close(a-b,x.gap);close(100*(a-b),x.gap_pp);close(n*(a-b),x.gap_questions);}
close(R.wilson(.5,100)[0],.4038315303659956);close(R.wilson(.5,100)[1],.5961684696340044);assert.throws(()=>R.wilson(NaN,10));assert.throws(()=>R.wilson(.5,0));assert.equal(R.verdict(0,.1),'no separation detected at this sample size');assert.equal(R.compare({N:10,score:50,interval_type:'unknown'},{N:10,score:40,interval_type:'unknown'}).unknown,true);
console.log('PASS: ten issue #39 fixtures directly verified; Wilson/Newcombe endpoints and minimum gaps to 1e-12, exact verdicts.');
const cache=require('../data/paired-cache.json'),manifest=require('../data/manifest.json');for(const f of fixtures.filter(x=>x.paired_verdict)){let found=false;for(const m of manifest){const c=require('../data/'+m.file);for(const s of c.sections){const a=s.rows.find(x=>x.configuration_id===f.configuration_id_A),b=s.rows.find(x=>x.configuration_id===f.configuration_id_B);if(!a||!b)continue;const key=R.pairedKey(a,b),v=cache[key];if(!v)continue;close(v.paired_lower,f.paired_lower);close(v.paired_upper,f.paired_upper);close(v.mcnemar_p,f.mcnemar_p);assert.equal(v.paired_verdict,f.paired_verdict);assert.equal(R.compare(a,b,cache).yes,f.paired_verdict==='separated');found=true;}}assert.ok(found,'Missing paired fixture '+f.comparison_id);}console.log('PASS: available paired fixture endpoints, McNemar p and precedence match frozen results.');

require("../src/paired.js");const dynamic=R.compare({N:4,protocol:"test",score:75,outcomes:{a:true,b:true,c:true,d:false}},{N:4,protocol:"test",score:25,outcomes:{a:false,b:false,c:false,d:true}},{});assert.equal(dynamic.type,"paired");assert.equal(dynamic.unknown,undefined);console.log("PASS: new uncached pair computes locally with paired precedence");
