const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');const archive=process.env.R9_ARCHIVE;if(!archive)throw Error('Set R9_ARCHIVE to the original work/leaderboard-noise/raw folder');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage();await page.route('**/*',r=>r.abort());await page.addScriptTag({content:fs.readFileSync(path.join(root,'bookmarklet/readers.js'),'utf8')});let total=0;
for(const m of JSON.parse(fs.readFileSync(path.join(root,'data/manifest.json')))){const c=JSON.parse(fs.readFileSync(path.join(root,'data',m.file)));if(c.kind!=='leaderboard')continue;const html=fs.readFileSync(path.join(archive,c.archive_source_id+'.html'),'utf8');assert.equal(crypto.createHash('sha256').update(html).digest('hex'),c.archived_html_sha256);const rows=await page.evaluate(({html,id})=>RankNoiseReaders.read(new DOMParser().parseFromString(html,'text/html'),id),{html,id:c.id});const want=c.sections[0].rows;
// Exact numeric/identifier rows, intervals and per-item matrices; notes are editorial metadata.
const canonical=r=>Object.fromEntries(['rank','model','score','N','configuration_id','protocol','outcomes','interval_type','interval','question_count_allowed','successes'].filter(k=>k in r).map(k=>[k,r[k]]));
try{assert.deepEqual(rows.map(canonical),want.map(canonical));}catch(e){console.error('READER DIFF',c.id);throw e;}console.log('PASS reader',c.id,rows.length);total+=rows.length;
}
assert.equal(await page.evaluate(()=>{try{RankNoiseReaders.read(new DOMParser().parseFromString('<html></html>','text/html'),'aider-polyglot');return false}catch(e){return e.message==="can't read this page"}}),true);assert.deepEqual(await page.evaluate(()=>RankNoiseReaders.forURL('https://labs.scale.com/leaderboard/swe_bench_pro_public_v2?tab=hard')),[]);await browser.close();console.log('PASS all nine readers:',total,'exact archived rows; malformed/unsupported input fails closed');})().catch(e=>{console.error(e);process.exit(1)});
