/* Frozen Wilson/Newcombe + audited source-interval precedence. No network. */
(function(root){
'use strict';
const Z=1.959963984540054;
function wilson(p,n){if(!Number.isFinite(p)||p<0||p>1||!Number.isInteger(n)||n<1)throw Error('Invalid binomial inputs');const d=1+Z*Z/n,c=(p+Z*Z/(2*n))/d,h=Z*Math.sqrt(p*(1-p)/n+Z*Z/(4*n*n))/d;return [Math.max(0,c-h),Math.min(1,c+h)];}
function difference(a,b,n){const [la,ua]=wilson(a,n),[lb,ub]=wilson(b,n),d=a-b;return [d-Math.hypot(a-la,ub-b),d+Math.hypot(ua-a,b-lb)];}
function verdict(lo,hi){return lo>0||hi<0?'separated':'no separation detected at this sample size';}
function pairedKey(a,b){const aa=a.outcomes,bb=b.outcomes,n=a.N;if(!aa||!bb||n!==b.N||!a.protocol||a.protocol!==b.protocol||a.protocol.includes('unknown'))return null;const keys=Object.keys(aa).sort();if(keys.length!==n||Object.keys(bb).length!==n||keys.some(k=>typeof aa[k]!=='boolean'||typeof bb[k]!=='boolean'))return null;const pa=keys.reduce((v,k)=>v+Number(aa[k]),0)/n,pb=keys.reduce((v,k)=>v+Number(bb[k]),0)/n;if(Math.abs(pa-a.score/100)>.00051||Math.abs(pb-b.score/100)>.00051)return null;const counts=[0,0,0,0];keys.forEach(k=>counts[Number(aa[k])*2+Number(bb[k])]++);return counts.join(',');}
function marginal(a){if(a.interval&&a.interval.length===2&&a.interval.every(Number.isFinite))return a.interval;if(a.interval_type==='wilson')return wilson(a.score/100,a.N);return null;}
function compare(a,b,cache={}){if(a===b)return {yes:false,reason:'Reference row',type:'reference'};if(a.N!==b.N)return {yes:false,unknown:true,reason:'Different item sets / N; cannot calculate'};const key=pairedKey(a,b);if(key){const x=cache[key];if(!x)return {yes:false,unknown:true,reason:'Matching per-item data require a new frozen-seed paired bootstrap; unavailable locally'};if(Array.isArray(x))return {yes:x[2],lo:x[0],hi:x[1],type:'paired',reason:'Paired McNemar + PCG64 bootstrap (100,000; seed 20261007)'};return {yes:x.paired_verdict==='separated',reason:'Paired McNemar + PCG64 bootstrap (100,000; seed 20261007)',type:'paired',lo:x.paired_lower,hi:x.paired_upper};}const ia=marginal(a),ib=marginal(b);if(!ia||!ib)return {yes:false,unknown:true,reason:"can’t calculate from published data"};let lo,hi;if(a.interval_type==='wilson'&&b.interval_type==='wilson'){[lo,hi]=difference(a.score/100,b.score/100,a.N);return {yes:verdict(lo,hi)==='separated',lo,hi,reason:'Independent Newcombe / Wilson working item interval',type:'wilson'};}lo=ia[0]-ib[1];hi=ia[1]-ib[0];return {yes:verdict(lo,hi)==='separated',lo,hi,reason:'Source marginal interval nonoverlap sensitivity; not a joint 95% difference interval',type:'source'};}
function gap(a,b){if(a.question_count_allowed&&b.question_count_allowed&&Number.isInteger(a.successes)&&Number.isInteger(b.successes)&&a.N===b.N)return `${a.successes-b.successes} questions`;return `${(a.score-b.score).toFixed(2)} pp`;}
const api={Z,wilson,difference,verdict,pairedKey,marginal,compare,gap};if(typeof module!=='undefined')module.exports=api;root.RankNoise=api;
})(typeof globalThis==='undefined'?this:globalThis);
