(function(root){
'use strict';
function el(tag,text,cls){const e=document.createElement(tag);if(text!==null&&text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function renderCard(card,cache){const article=el('article',null,'card');article.id=card.id;const head=el('header',null,'card-head');const top=el('div',card.kind==='launch'?'LAUNCH POST':'LEADERBOARD','eyebrow');head.append(top);const title=el('h2');const anchor=el('a',card.title);anchor.href='#'+card.id;title.append(anchor);head.append(title);const meta=el('p','Snapshot '+card.snapshot_date.slice(0,10)+' UTC · ','meta');const source=el('a','Source ↗');source.href=card.source_url;source.rel='noopener noreferrer';meta.append(source);head.append(meta);article.append(head);
 const grid=el('div',null,card.sections.length>1?'sections multiple':'sections');let unknown=false;
 for(const sec of card.sections){const block=el('section',null,'benchmark');if(card.sections.length>1)block.append(el('h3',sec.benchmark+' · N='+sec.N));else block.append(el('p','N='+sec.N+' distinct items · scores and intervals in %','scale-label'));const table=el('table');const thead=el('thead'),tr=el('tr');['Rank','Model','Score','Interval¹','Gap to #1','Distinguishable from #1'].forEach((t,i)=>tr.append(el('th',t,'c'+i)));thead.append(tr);table.append(thead);const tbody=el('tbody'),first=sec.rows[0];for(const row of sec.rows){const cmp=RankNoise.compare(first,row,cache);unknown=unknown||!!cmp.unknown;const line=el('tr',null,cmp.yes?'separated':'muted');line.append(el('td',row.rank,'rank'));const model=el('td',row.model,'model');model.title=row.notes||row.model;line.append(model);line.append(el('td',row.score.toFixed(2),'score'));const cell=el('td',null,'interval-cell'),bar=el('div',null,'bar'),iv=RankNoise.marginal(row);if(iv){const band=el('span',null,'band');band.style.left=(Math.max(0,iv[0])*100)+'%';band.style.width=((Math.min(1,iv[1])-Math.max(0,iv[0]))*100)+'%';bar.append(band);bar.title=iv.map(v=>(v*100).toFixed(2)).join('–')+'% · '+(row.interval_note||row.interval_type);}else{bar.classList.add('unavailable');bar.title='Interval unavailable';}const dot=el('span',null,'dot');dot.style.left=row.score+'%';bar.append(dot);cell.append(bar);line.append(cell);line.append(el('td',RankNoise.gap(first,row),'gap'));const decision=el('td',(cmp.yes?'yes':'no')+(cmp.unknown?'*':''),'decision');decision.title=cmp.reason;line.append(decision);tbody.append(line);}table.append(tbody);block.append(table);grid.append(block);}
 if(!card.sections.length)grid.append(el('p','No eligible headline table in this post.','empty'));article.append(grid);const foot=el('div',null,'card-foot');foot.append(el('p',card.note||''));foot.append(el('p','¹ Bars: Wilson working item intervals or matching source intervals, as audited. Source-bar nonoverlap is a sensitivity check; it is not a 95% pairwise test. Paired evidence takes precedence when available. Grey = separation not established.'));
 if(unknown)foot.append(el('p','* no — can’t calculate from published data (or unmatched item sets). A dot without a bar means the interval is unavailable.','missing-note'));
 const credit=el('p','Noise check by Maverick for Driftproof · ','credit');const method=el('a','method');method.href='#method-placeholder';method.title='Placeholder — piece URL to be added before launch';credit.append(method);foot.append(credit);article.append(foot);return article;}
root.RankNoiseRender={renderCard};
})(globalThis);
