(function(root){'use strict';
const text=e=>e.textContent.replace(/\s+/g,' ').trim();
function fail(){throw Error("can't read this page");}
function number(v){const n=Number(v);if(!Number.isFinite(n))fail();return n;}
function row(rank,model,score,N,id='',protocol='',outcomes=null){score=number(score)/100*100;if(!model||score<0||score>100||!Number.isInteger(N)||N<1)fail();return {rank,model,score,N,configuration_id:id,protocol,outcomes,interval_type:'wilson',interval:null,question_count_allowed:false,notes:''};}
function rsc(doc){let s='';for(const tag of doc.querySelectorAll('script')){const m=tag.textContent.match(/^\s*self\.__next_f\.push\(([\s\S]*)\)\s*;?\s*$/);if(!m)continue;let a;try{a=JSON.parse(m[1]);}catch{fail();}if(typeof a[1]==='string')s+=a[1];}if(!s)fail();return s;}
function valueAfter(s,key){const start=s.indexOf(key);if(start<0)fail();let i=start+key.length;while(/\s/.test(s[i]))i++;const open=s[i],close=open==='['?']':'}';if(open!=='['&&open!=='{')fail();let depth=0,str=false,escape=false;for(let j=i;j<s.length;j++){const c=s[j];if(str){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')str=false;}else{if(c==='"')str=true;else if(c===open)depth++;else if(c===close&&!--depth){try{return JSON.parse(s.slice(i,j+1));}catch{fail();}}}}fail();}
function aider(doc){const trs=[...doc.querySelectorAll('tr[id^="main-row-"]')].slice(0,15);if(!trs.length)fail();return trs.map((tr,i)=>{const detail=doc.getElementById('details-'+tr.id.split('-').pop());if(!detail)fail();const d={};for(const li of detail.querySelectorAll('li')){const t=text(li),at=t.indexOf(':');if(at>=0)d[t.slice(0,at).trim()]=t.slice(at+1).trim();}const cells=tr.querySelectorAll(':scope > td');if(cells.length<3||!d['Dirname'])fail();const r=row(i+1,text(cells[1]),text(cells[2]).replace('%',''),number(d['Test cases']),d.Dirname);const solved=number(d['Pass num 2']);if(Number.isInteger(solved)&&Math.abs(solved/r.N-r.score/100)<=.00051){r.successes=solved;r.question_count_allowed=true;}r.notes='Published rounded two-attempt repair success; attempts 1 and 2 are not independent runs.';return r;});}
const specs={ 'swe-bench-full':['Test',2294],'swe-bench-lite':['Lite',300],'swe-bench-multilingual':['Multilingual',300],'swe-bench-multimodal':['Multimodal',517],'swe-bench-verified-bash-only':['Verified',500],'swe-bench-verified-all-agents':['Verified',500]};
function swe(doc,id){const tag=doc.getElementById('leaderboard-data');if(!tag)fail();let data;try{data=JSON.parse(tag.textContent);}catch{fail();}const [name,n]=specs[id],g=data.find(x=>x.name===name);if(!g||!Array.isArray(g.results))fail();let es=g.results.filter(x=>!x.warning);if(id.endsWith('bash-only'))es=es.filter(x=>x.agent==='mini-SWE-agent');es.sort((a,b)=>b.resolved-a.resolved);if(!es.length)fail();return es.slice(0,15).map((x,i)=>{let outcomes=null;if(x.per_instance_details&&Object.keys(x.per_instance_details).length)outcomes=Object.fromEntries(Object.entries(x.per_instance_details).map(([k,v])=>[k,v.resolved]));const r=row(i+1,x.name,x.resolved,n,x.folder,(x.agent||'')+'|'+(x['mini-swe-agent_version']??'unknown'),outcomes);r.notes=(x.tags||[]).join('; ');if(outcomes&&Object.values(outcomes).every(x=>typeof x==='boolean')&&Object.keys(outcomes).length===n){const successes=Object.values(outcomes).filter(Boolean).length;if(Math.abs(successes/n-r.score/100)<=.00051){r.successes=successes;r.question_count_allowed=true;}}return r;});}
function terminal(doc){const data=valueAfter(rsc(doc),'"leaderboard":'); // leaderboard metadata alone; obtain complete outer object separately
const stream=rsc(doc),at=stream.indexOf('{"leaderboard":');if(at<0)fail();const full=valueAfter('!'+stream.slice(at),'!');if(full.leaderboard.title!=='Terminal-Bench 4.0'||!Array.isArray(full.rows))fail();return full.rows.slice().sort((a,b)=>a.rank-b.rank).slice(0,15).map((x,i)=>{const m=x.metadata,q=x.metrics;if(!m||!q||!Number.isFinite(q.accuracy_ci95_half_width))fail();const r=row(i+1,m.model_display.label+' / '+m.agent_display.label+' / '+m.reasoning_effort,q.accuracy,66,x.id);const h=q.accuracy_ci95_half_width/100;r.interval_type='published';r.interval=[r.score/100-h,r.score/100+h];r.notes='Official 95% CI; average of 5 attempts/task. Marginal nonoverlap sensitivity.';return r;});}
function pro(doc){const es=valueAfter(rsc(doc),'"entries":');if(!Array.isArray(es)||!es.length)fail();return es.slice(0,15).map((x,i)=>{const r=row(i+1,x.model,x.score,642,String(x.rank));r.notes='Rounded published score; exact repeated-run scores not available in this snapshot. Source ± is not defined sufficiently to use as a repeated-run 95% CI.';return r;});}
const registry={'aider-polyglot':aider,...Object.fromEntries(Object.keys(specs).map(k=>[k,doc=>swe(doc,k)])),'terminal-bench-4-0':terminal,'swe-bench-pro-v2-full':pro};
function read(doc,id){if(!registry[id])fail();const rows=registry[id](doc);if(!rows.length||rows.some(r=>!Number.isFinite(r.score)))fail();return rows;}
function forURL(url){const u=new URL(url);if(u.hostname==='aider.chat'&&u.pathname==='/docs/leaderboards/')return ['aider-polyglot'];if(['www.swebench.com','swebench.com'].includes(u.hostname)&&u.pathname==='/')return Object.keys(specs);if(['www.tbench.ai','tbench.ai'].includes(u.hostname)&&u.pathname==='/'&&(!u.searchParams.has('version')||u.searchParams.get('version')==='4.0'))return ['terminal-bench-4-0'];if(u.hostname==='labs.scale.com'&&u.pathname==='/leaderboard/swe_bench_pro_public_v2'&&(!u.searchParams.has('tab')||u.searchParams.get('tab')==='full'))return ['swe-bench-pro-v2-full'];return [];}
root.RankNoiseReaders={read,forURL,ids:Object.keys(registry)};if(typeof module!=='undefined')module.exports=root.RankNoiseReaders;
})(globalThis);
